services:
  - type: web
    name: tactiball-pro-v3
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: tactiball-pro-v3
          property: host
    healthCheckPath: /health
    autoDeploy: false
